name: Publish docs (GH pages)

on:
  push:
    branches: [master]

jobs:
  build-publish-docs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: artus9033/MNultitool/.github/actions/setup@master

      - name: Build docs
        run: cd ./scripts && PATH="$HOME/.local/bin:$PATH" source buildDocs.bash

      - name: Deploy docs to GH Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/build/html/
          enable_jekyll: false
          allow_empty_commit: false
          force_orphan: true
          publish_branch: gh-pages
