name: Generate docs

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [master]

jobs:
  publish-docs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: ./github/actions/setup.yml

      - name: Build docs
        run: cd ./scripts && PATH="$HOME/.local/bin:$PATH" source buildDocs.bash

      - name: Deploy docs to GH Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/build/html/
          enable_jekyll: false
          allow_empty_commit: false
          force_orphan: true
          publish_branch: gh-pages

  publish-package:
    steps:
      - uses: actions/checkout@v2

      - uses: ./github/actions/setup.yml

      - name: Build package
        run: cd scripts && PATH="$HOME/.local/bin:$PATH" source package.bash

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@master
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
